<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Заявление на бюджет</h1><br/>
    <h1>Прошу зачислить меня на бюджет, студента</h1>
    <h3>${name} ${surname} ${patronymic}</h3>
    <p>Начиная с ${from}</p>
</body>
</html>