version: "3.2"

services:
  easypdf:
    build: 
      context: $PWD/EasyPDF
    ports:
      - "8080:8080"
    env_file: $PWD/easypdf.env
    depends_on:
      - redis
      - postgres
      - rabbitmq
  generatorpdf:
    build:
      context: $PWD/PdfGenerator
    env_file: $PWD/generator.env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia/
  redis:
    image: redis
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data
  postgres:
    image: postgres:13.3
    env_file: $PWD/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data

volumes:
  redis_data:
    external: true
  rabbit_data:
    external: true
